### ISSUE TITLE
Basic check for leaf

### ISSUE THREAD

**Issue by BioQwer** [frost-nzcr4/find_forks#7]
Hello @frost-nzcr4 .
For example, my local repo it's fork of more popular repo. My repo has't fork.
I want to get all forks of more popular repo that has changes but not merged in to popular repo.
Can you add this feature?

**Comment by BioQwer** [comment]
I find GitHub method to find forks with some changes, but them secure.
Method don't work where large forks count, but for little repo is good.
`https://github.com/:user/:repo/network/meta`

![image](https://cloud.githubusercontent.com/assets/5636129/14638014/911e3e6c-064e-11e6-8302-d073de001a3d.png)

**Comment by frost-nzcr4** [comment]
Did you try command to remove all merged forks `git branch -r --merged | grep -v -e "\(origin\|upstream\|BioQwer\)/" | xargs -n 1 git branch -r -d` described in #1?

The command is basically ok, until some `user1` has made changes to upstream and other `user2` forks from this one, then git thinks that they both made the changes and both forks will still exist, but only fork of `user1`'s should.

To prevent this kind of duplicates:
- command to remove all merged forks should run on every branch automatically, or
- [Commits API](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository) can be used

I think it's a task for git rather than github.

**Comment by BioQwer** [comment]
Before you say don't.
Thanks you it't cool clean up. I can add as default behavior after find all forks.
How i can clean up unmerged duplicates branches?

**Comment by frost-nzcr4** [comment]
Try this script:

``` shell
for BRANCH in $( git branch -r --no-color | cut -d" " -f3 ); do
    git checkout "$BRANCH"
    git branch -r --merged | grep -v -e "\(origin\|upstream\|BioQwer\)/" | xargs -n 1 git branch -r -d
done
```

all duplicates should be removed.

**Comment by BioQwer** [comment]
All ok.
